package com.add.databoject;

import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class SequenceDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Thu Nov 04 20:25:00 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbg.generated Thu Nov 04 20:25:00 CST 2021
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Thu Nov 04 20:25:00 CST 2021
     */
    private Integer step;

    private Integer maxValue;

    private Integer initValue;

}